### ISSUE TITLE
fabric.mod.json version number is incorrect

### ISSUE THREAD

**Issue by ViciousBadger** [klinbee/MoreDensityFunctions#1]
Hello, first off, thanks for creating this!!!!

I am creating a datapack (packaged as a mod) that depends on MoreDensityFunctions and the version number reported by the mod is still 1.0.0 instead of 1.0.4 as it should be. This makes so I cannot to force users to install the correct version of MoreDensityFunctions, which I really want to do because the different versions are not compatible with each other!

**Comment by Quidvio** [comment]
That's a pretty big issue, thanks for bringing it up. I'll fix it whenever I get home from work today. Thanks.

**Comment by klinbee** [comment]
I ended up forgetting about this (job moment)

Fixed in the latest version, will be updating other versions as well.
