### ISSUE TITLE
1.19.2 forge?

### ISSUE THREAD

**Issue by mateus3c** [klinbee/MoreDensityFunctions#2]
Hi I tried playing with the Larion datapack but it requires this mod but it's only available for fabric 1.19.2 even tho Larion has a datapack version for 1.19.2

Do you plan making a version of the mod for forge 1.19.2?

**Comment by klinbee** [comment]
Very busy at the moment, but I recently had someone comission Forge 1.20.1, which means it shouldn't be that bad to make a backport to 1.19.2. It'll be on my calendar, but I have higher priorities atm.
